owner: omeroastore-ops
repo: uptime-monitor

sites:
  - name: Secret Bar Menu
    url: https://secretbar-bs.de/?menu=true

  - name: Safe Bar Menu
    url: https://safe-bs.de/#/menu

  - name: Brackwasser Cinema
    url: https://omeroastore-ops.github.io/brackwasser-cinema/

  - name: KARO Kebab Menu
    url: https://omeroastore-ops.github.io/KAROKEBABHOUSE/#menu

status-website:
  baseUrl: /uptime-monitor
  name: Status Monitor
  introTitle: "Website Status"
  introMessage: "Monitoring all my client websites automatically."
  navbar:
    - title: Status
      href: /
